# Generated by Django 3.0.8 on 2021-06-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
