# Generated by Django 3.0.8 on 2021-06-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
