# Generated by Django 3.0.8 on 2021-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210609_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255)),
                ('Age', models.IntegerField(blank=True, max_length=3)),
            ],
        ),
    ]
