# Generated by Django 3.0.8 on 2021-06-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20210609_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Age',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
