# Generated by Django 3.0.8 on 2021-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20210609_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
